python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-70to100.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-100to200.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-200to400.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-400to600.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-600to800.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-800to1200.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-1200to2500.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/DYJetsToLL_M-50_HT-2500toInf.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/WJetsToLNu.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/QCD_500to700.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/QCD_700to1000.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/QCD_1000to1500.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/QCD_1500to2000.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/QCD_2000toInf.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/ST_s-channel_4f_leptonic.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/ST_t-channel_antitop_inclusive.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/ST_t-channel_top_inclusive.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/ST_tW_antitop_5f_inclusive.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/ST_tW_top_5f_inclusive.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/TT_Tune.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/TT_M1000.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/TT_M1500.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/TT_M2000.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/TT_M2500.root &
python ntuple_btagCut.py /eos/uscms/store/user/kpal/trimmed_files_v4/TT_M3000.root &
