python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/DY1Jets_MLL-50_btag.root                 &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/DY2Jets_MLL-50_btag.root                 &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/DY3Jets_MLL-50_btag.root                 &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/QCD_1000to1500_btag.root                 &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/QCD_1500to2000_btag.root                 &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/QCD_2000toInf_btag.root                  &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/QCD_500to700_btag.root                   &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/QCD_700to1000_btag.root                  &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/ST_s-channel_4f_leptonic_btag.root       &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/ST_t-channel_antitop_inclusive_btag.root &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/ST_t-channel_top_inclusive_btag.root     &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/ST_tW_antitop_5f_inclusive_btag.root     &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/ST_tW_top_5f_inclusive_btag.root         &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_Mtt-1000toInf_btag.root               &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/WJetsToLNu_btag.root                     &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_Tune_btag.root                        &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M1000_btag.root                       &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M1500_btag.root                       &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M2000_btag.root                       &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M2500_btag.root                       &
python ntuple_lepton_bifurcation.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M3000_btag.root                       &
