python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/TT_M1000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/TT_M1500_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/TT_M2000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/TT_M2500_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/TT_M3000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/e_channel/qcd_btag_plot.root

python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/TT_M1000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/TT_M1500_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/TT_M2000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/TT_M2500_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/qcd_btag_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/TT_M3000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3.1/u_channel/qcd_btag_plot.root
