#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M1000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M1500_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M2000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M2500_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M3000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
#
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/TT_M1000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/TT_M1500_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/TT_M2000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/TT_M2500_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/TT_M3000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2.2.2/st/35.9/qcd_plot.root
