python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M1000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M1500_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M2000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M2500_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/TT_M3000_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/top_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/ew_plot.root /eos/uscms/store/user/kpal/trimmed_files_v2/35.9/qcd_plot.root
#
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M1000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/qcd_btag_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M1500_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/qcd_btag_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M2000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/qcd_btag_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M2500_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/qcd_btag_plot.root
#python st_histogram.py /eos/uscms/store/user/kpal/trimmed_files_v3/TT_M3000_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/top_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/ew_btag_plot.root /eos/uscms/store/user/kpal/trimmed_files_v3/qcd_btag_plot.root
