#import contextlib2
import ROOT
import sys

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
f = ROOT.TFile.Open(sys.argv[1], 'read')
g = ROOT.TFile.Open(sys.argv[2], 'read')

hists = {}
hists_g = {}
#reading very many histrograms
hists["electrons_pt"] = f.Get("electrons_pt")
hists["electrons_eta"] = f.Get("electrons_eta")
hists["electrons_phi"] = f.Get("electrons_phi")
hists["electrons_mass"] = f.Get("electrons_mass")
hists["TightElectrons_pt"] = f.Get("TightElectrons_pt")
hists["TightElectrons_eta"] = f.Get("TightElectrons_eta")
hists["TightElectrons_phi"] = f.Get("TightElectrons_phi")
hists["TightElectrons_mass"] = f.Get("TightElectrons_mass")
hists["muons_pt"] = f.Get("muons_pt")
hists["muons_eta"] = f.Get("muons_eta")
hists["muons_phi"] = f.Get("muons_phi")
hists["muons_mass"] = f.Get("muons_mass")
hists["TightMuons_pt"] = f.Get("TightMuons_pt")
hists["TightMuons_eta"] = f.Get("TightMuons_eta")
hists["TightMuons_phi"] = f.Get("TightMuons_phi")
hists["TightMuons_mass"] = f.Get("TightMuons_mass")
hists["gammas_pt"] = f.Get("gammas_pt")
hists["gammas_eta"] = f.Get("gammas_eta")
hists["gammas_phi"] = f.Get("gammas_phi")
hists["gammas_mass"] = f.Get("gammas_mass")
hists["taus_pt"] = f.Get("taus_pt")
hists["taus_eta"] = f.Get("taus_eta")
hists["taus_phi"] = f.Get("taus_phi")
hists["taus_mass"] = f.Get("taus_mass")
hists["jetspuppi_pt"] = f.Get("jetspuppi_pt")
hists["jetspuppi_eta"] = f.Get("jetspuppi_eta")
hists["jetspuppi_phi"] = f.Get("jetspuppi_phi")
hists["jetspuppi_mass"] = f.Get("jetspuppi_mass")
hists["jetspuppi_multiplicity"] = f.Get("jetspuppi_multiplicity")
hists["jetspuppi_btagmultiplicity"] = f.Get("jetspuppi_btagmultiplicity")
hists["jetspuppi_Ht"] = f.Get("jetspuppi_Ht")
hists["fatjets_pt"] = f.Get("fatjets_pt")
hists["fatjets_eta"] = f.Get("fatjets_eta")
hists["fatjets_phi"] = f.Get("fatjets_phi")
hists["fatjets_mass"] = f.Get("fatjets_mass")
hists["metspuppi_pt"] = f.Get("metspuppi_pt")
hists["metspuppi_phi"] = f.Get("metspuppi_phi")

hists_g["electrons_pt"] = g.Get("electrons_pt")
hists_g["electrons_eta"] = g.Get("electrons_eta")
hists_g["electrons_phi"] = g.Get("electrons_phi")
hists_g["electrons_mass"] = g.Get("electrons_mass")
hists_g["TightElectrons_pt"] = g.Get("TightElectrons_pt")
hists_g["TightElectrons_eta"] = g.Get("TightElectrons_eta")
hists_g["TightElectrons_phi"] = g.Get("TightElectrons_phi")
hists_g["TightElectrons_mass"] = g.Get("TightElectrons_mass")
hists_g["muons_pt"] = g.Get("muons_pt")
hists_g["muons_eta"] = g.Get("muons_eta")
hists_g["muons_phi"] = g.Get("muons_phi")
hists_g["muons_mass"] = g.Get("muons_mass")
hists_g["TightMuons_pt"] = g.Get("TightMuons_pt")
hists_g["TightMuons_eta"] = g.Get("TightMuons_eta")
hists_g["TightMuons_phi"] = g.Get("TightMuons_phi")
hists_g["TightMuons_mass"] = g.Get("TightMuons_mass")
hists_g["gammas_pt"] = g.Get("gammas_pt")
hists_g["gammas_eta"] = g.Get("gammas_eta")
hists_g["gammas_phi"] = g.Get("gammas_phi")
hists_g["gammas_mass"] = g.Get("gammas_mass")
hists_g["taus_pt"] = g.Get("taus_pt")
hists_g["taus_eta"] = g.Get("taus_eta")
hists_g["taus_phi"] = g.Get("taus_phi")
hists_g["taus_mass"] = g.Get("taus_mass")
hists_g["jetspuppi_pt"] = g.Get("jetspuppi_pt")
hists_g["jetspuppi_eta"] = g.Get("jetspuppi_eta")
hists_g["jetspuppi_phi"] = g.Get("jetspuppi_phi")
hists_g["jetspuppi_mass"] = g.Get("jetspuppi_mass")
hists_g["jetspuppi_multiplicity"] = g.Get("jetspuppi_multiplicity")
hists_g["jetspuppi_btagmultiplicity"] = g.Get("jetspuppi_btagmultiplicity")
hists_g["jetspuppi_Ht"] = g.Get("jetspuppi_Ht")
hists_g["fatjets_pt"] = g.Get("fatjets_pt")
hists_g["fatjets_eta"] = g.Get("fatjets_eta")
hists_g["fatjets_phi"] = g.Get("fatjets_phi")
hists_g["fatjets_mass"] = g.Get("fatjets_mass")
hists_g["metspuppi_pt"] = g.Get("metspuppi_pt")
hists_g["metspuppi_phi"] = g.Get("metspuppi_phi")

outputDir = '/eos/user/k/kpal/www/qcd_signal/'
legend = ROOT.TLegend(0.7,0.8,0.91,0.91) #legend in top right corner
for h in hists.keys():
    canvas = ROOT.TCanvas('canvas','',700,500)
    hists[h].SetLineColor(3)
    hists[h].SetFillColor(3)
    hists[h].Draw("hist")
    hists_g[h].Draw("same hist")
    legend.AddEntry(hists[h],"QCD")
    legend.AddEntry(hists_g[h],"TT signal")
    legend.Draw()
    canvas.SaveAs(outputDir + h + ".pdf")
    canvas.Close()
    legend.Clear()


f.Close()
g.Close()
